### ISSUE TITLE
Diagrama de Clase (Componentes)

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#11]

**Comment by Pandaluf** [comment]
[Diagrama de Clases (Componentes).docx](https://github.com/Julio12-prog/TF_Algoritmos/files/6681306/Diagrama.de.Clases.Componentes.docx)

**Comment by Julio12-prog** [comment]
![diagrama - Página 3](https://user-images.githubusercontent.com/73925470/122660975-6019fb80-d14b-11eb-929d-f08f0ef415fe.jpeg)
![diagrama - Página 4](https://user-images.githubusercontent.com/73925470/122660977-60b29200-d14b-11eb-9192-9995aae6b6f8.jpeg)
![diagrama - Página 2](https://user-images.githubusercontent.com/73925470/122660978-60b29200-d14b-11eb-997b-02729685a245.jpeg)

**Comment by Julio12-prog** [comment]
Completado y revisado.
