### ISSUE TITLE
Elaboración del código Config

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#14]

**Comment by Pandaluf** [comment]
void config(string _cadena) {
		string registro = _cadena;
		string cidusu;
		string cmail;
		string ccodigo;
		stringstream archMemoria(registro);
		getline(archMemoria, cidusu, ',');
		getline(archMemoria, cmail, ',');
		getline(archMemoria, ccodigo, '\n');
		_config(cidusu, cmail, ccodigo);
	}

	void _config(string _id_Usu, string _mail, string _codigo) {
		this->usuario_1->setIdUsuario(_id_Usu);
		this->usuario_1->setCoreo(_mail);
		this->usuario_1->setCod(stoi(_codigo));
		cout << "\n>Usuario configurado!\n";
		cout << usuario_1->MostrarUsuario();
	}

**Comment by Julio12-prog** [comment]
Revisado y completado
