### ISSUE TITLE
Elaboración del código init

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#15]

**Comment by Julio12-prog** [comment]
Avance Init        
        void init() {
		string ruta_absoluta = "D:/Repository";
		if (_mkdir(ruta_absoluta.c_str()) == 0) {
			cout << "\n>Repositorio creado correctamente!" << endl;
		}
	}

**Comment by Julio12-prog** [comment]
Revisado y completado
