### ISSUE TITLE
Elaboración del código Clone

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#16]

**Comment by Pandaluf** [comment]
Código:

void _Clone(string ruta, string destino)
	{
		size_t carpeta_clone = ruta.rfind("\\");

		if (carpeta_clone != string::npos)
		{
			destino = destino + "\\" + ruta.substr(carpeta_clone + 1) + "_Clone";
		}

		if (_mkdir(destino.c_str()) == 0) {
			cout << "\n>Repositorio clonado correctamente!" << endl;
		}

		string cadena;
		cadena = "xcopy " + ruta + " " + destino + " /H /S";

		system(cadena.c_str());
	}

	void Clone(string _ruta) {
		string destino = "D:\WorkStation";
		_Clone(_ruta, destino);
	}

**Comment by Julio12-prog** [comment]
Revisado y completado
