### ISSUE TITLE
Elaboración del código Status

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#17]

**Comment by Julio12-prog** [comment]
Avance status-
void status() {
		queue<string> _cola_mods;
		_cola_mods = cola_1;
		cout << "\n>Archivos modificados preparados para proxima confirmacion!\n";
		while (_cola_mods.empty() == 0)
		{
			string _rule = _cola_mods.front();
			cout << "->[ " + _rule + " ]\n";
			_cola_mods.pop();
		}
	}

**Comment by Pandaluf** [comment]
Revisado y completado

**Comment by Pandaluf** [comment]
Revisado y completado
