### ISSUE TITLE
Elaboración del código Add

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#18]

**Comment by Pandaluf** [comment]
Código:

void add(string _nomArchivo) {
		string cadena;

		cadena = "copy D:\\WorkStation\\" + _nomArchivo + " " + "D:\\Index";

		system(cadena.c_str());

		preparacionImg(_nomArchivo);
	}

**Comment by Julio12-prog** [comment]
Revisado y completado
