### ISSUE TITLE
Elaboración del código Reset

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#19]

**Comment by Julio12-prog** [comment]
Avance Reset-
void reset(string _nomArchivo) {
		string cadena;
		cadena = "del D:\\Repository\\" + _nomArchivo;
		
		/* Ejecutar el comando */
		system(cadena.c_str());
		cola_1.pop();
	}

**Comment by Pandaluf** [comment]
Revisado y completado
