### ISSUE TITLE
Elaboración del código Diff

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#20]

**Comment by Julio12-prog** [comment]
Avance
void _diff(string _nomArchivo1) {
		string _nomArchivo2 = _nomArchivo1;
		string cadena;
		cadena = "FC D:\\WorkStation\\" + _nomArchivo1+" "+ "D:\\Index\\"+_nomArchivo2+" /N";

		/* Ejecutar el comando */
		system(cadena.c_str());				
	}

	void diff(string _nomArchivo1) {
		ifstream f1, f2;
		string s1, s2;
		f1.open("D:/WorkStation/" + _nomArchivo1);
		f2.open("D:/Index/" + _nomArchivo1);
		while (getline(f1, s1)) {
			do
			{
				getline(f2, s2);	
				if (s1.compare(s2) == 0)
				{
					cout << setw(10) << left << "[=]" << left << setw(50) << s1 << setw(50) << s2 << endl; break;
				}
				else
				{
					cout << setw(10) << "[!=]" << left << setw(50) << s1 << setw(50) << s2 << endl; break;
				}
			} while (true);
		}
	}

**Comment by Pandaluf** [comment]
Revisado y completado
