### ISSUE TITLE
Elaboración del código Commit-m

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#21]

**Comment by Julio12-prog** [comment]
Avance
void _commit_m() {
		
		string _rutaI = "D:\\Index";
		string _rutaR = "D:\\Repository";
		/* String para crear el comando: xcopy ruta destino */
		string cadena;
		//copia archivos ocultos[/H]; archivos y subcarpetas[/S]; sin confirmacion [/Y]
		cadena = "xcopy " + _rutaI + " " + _rutaR + " /H /S /Y";

		/* Ejecutar el comando */
		system(cadena.c_str());
	}

	void commit_m(string _message) {
		_commit_m();
		capturar_date(_message);

		while (cola_1.empty()==0) {
			cola_1.pop();
		}		
	}

	void capturar_date(string _message) {
		time_t ltime;
		time(&ltime);

		cola_dates.push(ltime);
		cola_messages.push(_message);
		cola_usu.push(usuario_1->MostrarUsuario());

	}

**Comment by Pandaluf** [comment]
Revisado y completado
