### ISSUE TITLE
Elaboración del código Log

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#22]

**Comment by Julio12-prog** [comment]
Avance
void log() {
		queue<time_t> cola_dates_clone;
		queue<G> cola_messag_clone;
		queue<G> cola_usu_clone;
		cola_dates_clone = cola_dates;
		cola_messag_clone = cola_messages;
		cola_usu_clone = cola_usu;

		while (cola_dates_clone.empty() == 0)
		{
			string _message = cola_messag_clone.front();

			errno_t err;
			err = _wctime_s(buf1, SIZE, &cola_dates_clone.front());

			if (err != 0) {
				printf("Invalid Arguments for _wctime_s. Error Code: %d\n", err);
				cout << endl;														
			}

			//Usuario* usuAutor = cola_usu_clone.front();
			cout << ">Autor:   " + cola_usu_clone.front();
			cout << ">Mensaje: " + _message + "\n";
			wprintf_s(L">Fecha de realizacion: %s\n", buf1);						
			cola_dates_clone.pop();
			cola_messag_clone.pop();
			cola_usu_clone.pop();
		}
	}

**Comment by Pandaluf** [comment]
Revisado y completado

**Comment by Pandaluf** [comment]
Revisado y completado
