### ISSUE TITLE
Elaboración del código Hash

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#23]

**Comment by Pandaluf** [comment]
**La clase HashTable:** 


class HT {
private:
	string* nombre;
	int tam;
	int indice;
	int contador;
public:
	HT() {
		tam = 10;
		nombre = new string[tam];
		for (int i = 0; i < tam; i++) {
			nombre[i] = " ";
		}
		indice = 0;
		contador = 0;
	}

	int hash(int key) {
		return key % 10;
	}

	void insert(string valor) {
		int key = 0;
		const char* arreglo;

		arreglo = valor.c_str();

		for (int i = 0; i < valor.size(); i++) {
			key = key + int(arreglo[i]);
		}

		indice = hash(key);

		while (nombre[indice] != " ") {
			indice++;
			if (indice == tam) {
				indice = 0;
			}
		}

		nombre[indice] = valor;
	}

	int search(string valor) {
		int c = 0;
		int key = 0;
		const char* arreglo;

		arreglo = valor.c_str();

		for (int i = 0; i < valor.size(); i++) {
			key = key + int(arreglo[i]);
		}

		int indice = hash(key);

		while (nombre[(indice + c) % 10] != valor) {
			c++;
		}

		return (indice + c) % 10;
	}

	string Mostrar(int ind) {
		return nombre[ind];
	}
};



**El código Hash:**

void hash(string _archivo) {
		hash_t->insert(_archivo);

		cout << "\n>hash-> " << hash_t->search(_archivo);
	}

**Comment by Julio12-prog** [comment]
Revisado y completado
