### ISSUE TITLE
Elaboración del código Show

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#24]

**Comment by Julio12-prog** [comment]
Avance
void _show(string _nomArch) {
		string s1;
		string _ruta = "D:/WorkStation/" + _nomArch;
		ifstream f1(_ruta);

		
		while (getline(f1, s1)) {	
			cout << s1 << endl;
		}
	}

	void show(int _hash) {
		string _st_arch = hash_t->Mostrar(_hash);
		_show(_st_arch);
	}

**Comment by Pandaluf** [comment]
Revisado

**Comment by Pandaluf** [comment]
Revisado y completado
