### ISSUE TITLE
Elaboración del código Rm

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#25]

**Comment by Pandaluf** [comment]
Código:

void rm(string _nomArchivo) {
		string cadena;
		cadena = "del D:\\Index\\" + _nomArchivo;
		/* Ejecutar el comando */
		system(cadena.c_str());

		cadena = "del D:\\WorkStation\\" + _nomArchivo;
		/* Ejecutar el comando */
		system(cadena.c_str());

		cola_1.pop();
	}

**Comment by Julio12-prog** [comment]
Revisado y completado.
