### ISSUE TITLE
Elaboración del código Mv

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#26]

**Comment by Pandaluf** [comment]
Código

void _mv(string _cadena) {
		string registro = _cadena;
		string campo1;							//nombre archivo
		string campo2;							//Ruta pegado
		stringstream archMemoria(registro);
		getline(archMemoria, campo1, '-');
		getline(archMemoria, campo2, '\n');
		mv(campo1, campo2);
	}

	void mv(string _nomArchivo, string _ruta) {
		string cadena;

		cadena = "move D:\\WorkStation\\" + _nomArchivo + " " + _ruta;
		/* Ejecutar el comando */
		system(cadena.c_str());
	}

**Comment by Julio12-prog** [comment]
Revisado y completado
