### ISSUE TITLE
Elaboración del código Stash

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#27]

**Comment by Julio12-prog** [comment]
Avance stash
void stash() {

		string _archivo = "stash.txt";
		string _texto;
		string ruta = "D:/Stash/" + _archivo;

		queue<string> _cola_mods;
		_cola_mods = cola_1;

		while (_cola_mods.empty() == 0)
		{
			string _rule = _cola_mods.front();
			_texto += "->[ " + _rule + " ]\n";
			_cola_mods.pop();
		}
		
		fstream aniadirArch;
		aniadirArch.open(ruta.c_str(), ios::app);
		aniadirArch << _texto << endl;
		aniadirArch.close();		
	}

**Comment by Pandaluf** [comment]
Revisado y completado

**Comment by Pandaluf** [comment]
Revisado y completado
