### ISSUE TITLE
Elaboración del código Stash list

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#28]

**Comment by Pandaluf** [comment]
Código:


	void stash_list() {

		string _archivo = "stash.txt";
		string _texto;
		string ruta = "D:/Stash/" + _archivo;

		fstream aniadirArch;
		aniadirArch.open(ruta.c_str(), ios::in);
		while (getline(aniadirArch, _texto)) {
			_stak_mods.push(_texto);
		}
		aniadirArch.close();

		stack<string> _clone = _stak_mods;

		_clone.pop();
		while (_clone.empty() == 0) {
			cout << "\nCambios en " << _clone.top();
			_clone.pop();
		}
		cout << endl;
	}

**Comment by Julio12-prog** [comment]
Revisado y completado
