### ISSUE TITLE
Desarrollar el Power Point

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#32]

**Comment by Julio12-prog** [comment]
[TF__PPT_Presentacion.pdf](https://github.com/Julio12-prog/TF_Algoritmos/files/6725800/TF__PPT_Presentacion.pdf)
[TF__PPT_Presentacion.pptx](https://github.com/Julio12-prog/TF_Algoritmos/files/6725801/TF__PPT_Presentacion.pptx)

**Comment by Pandaluf** [comment]
Revisado y Completado
