### ISSUE TITLE
Conclusiones

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#33]

**Comment by Julio12-prog** [comment]
Avance Conclusiones
- Conocemos el concepto de un sistema control de versiones gracias a la distintas fuentes académicas y la documentación de GitHub.
- Logramos comprender, en gran parte, las diferentes razones por las cuales elegir una estructura de datos por encima de otra en distintas ocasiones.
- Identificamos y creamos tipos de datos abstractos necesarios para llevar a cabo nuestra solución de manera optima y eficaz.
- Procesamos grandes cantidades de archivos por diferentes espacios de trabajo cumpliendo los criterios de un sistema control de versiones.
- Desarrollamos satisfactoriamente la aplicación con el diseño de propuesta aplicando una estrategia para la solución del problema planteado.

**Comment by Pandaluf** [comment]
Revisado y Completado
