### ISSUE TITLE
Mejora del diagrama de clases

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#34]

**Comment by Julio12-prog** [comment]
Mejora Diagrama de clases

![diagrama_SCV_TF](https://user-images.githubusercontent.com/73925470/123610348-1e7df600-d7c6-11eb-9050-44f0d95a8bed.jpeg)

**Comment by Julio12-prog** [comment]
![Diagrama_compo_Estruct](https://user-images.githubusercontent.com/73925470/123618353-ba5f3000-d7cd-11eb-8526-9760ed8b1f16.jpeg)

**Comment by Pandaluf** [comment]
Revisado y Completado
