### ISSUE TITLE
Elaboración del código Echo

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#35]

**Comment by Julio12-prog** [comment]
Avance
void _echo(string _texto, string _archivo) {
		string ruta = "D:/WorkStation/" + _archivo;

		fstream aniadirArch;
		aniadirArch.open(ruta.c_str(), ios::app);
		aniadirArch << _texto << endl;
		aniadirArch.close();

	}

	void echo(string _linea) {
		// echo- hola como esta esta es una linea[TEXTO] > prueba.cpp[ARCHIVO]
		// 1-> Recibo la linea entera
		// 2-> Separo la linea en NOMBRE D EARCHIVO y TEXTO A ESCRIBIR
		// 3-> Mandar a _echo(TEXTO; NOMBRE ARCHIVO)

		string registro = _linea;
		string campo1;
		string campo2;
		stringstream archMemoria(registro);
		getline(archMemoria, campo1, '-');
		getline(archMemoria, campo2, '\n');

		_echo(campo1,campo2);
	}

**Comment by Pandaluf** [comment]
Revisado y completado
