### ISSUE TITLE
Elaboración del código Touch

### ISSUE THREAD

**Issue by Pandaluf** [Julio12-prog/TF_Algoritmos#36]

**Comment by Julio12-prog** [comment]
Avance
void touch(string _nomArch) {
		errno_t err;
		FILE* stream;
		string _orden = "D:/WorkStation/" + _nomArch;
		err = fopen_s(&stream, _orden.c_str(), "w+");
		if (err == 0) { cout << "\n>Archivo creado!"; }
		err = fclose(stream);
	}

**Comment by Pandaluf** [comment]
Revisado y completado
