### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by Julio12-prog** [Julio12-prog/TF_Algoritmos#6]
[Diagrama en blanco.pdf](https://github.com/Julio12-prog/TF_Algoritmos/files/6653103/Diagrama.en.blanco.pdf)

**Comment by Pandaluf** [comment]
![diagrama](https://user-images.githubusercontent.com/85914860/122653619-638d9280-d10b-11eb-9132-0b101acbbaf8.png)

**Comment by Pandaluf** [comment]
este diagrama esta completo, falta revisar

**Comment by Julio12-prog** [comment]
![diagrama - Página 1](https://user-images.githubusercontent.com/73925470/122660972-51334900-d14b-11eb-9e9e-cddff86befa2.jpeg)
Diagrama mejorado.

**Comment by Julio12-prog** [comment]
Completado y revisado.
