### ISSUE TITLE
Implementación de estructuras de datos

### ISSUE THREAD

**Issue by Julio12-prog** [Julio12-prog/TF_Algoritmos#9]
Desarrollo de la estructuras de datos.

**Comment by Pandaluf** [comment]
[Estruct.txt](https://github.com/Julio12-prog/TF_Algoritmos/files/6653256/Estruct.txt)

**Comment by Pandaluf** [comment]
[Implementacion de las estructuras de datos.docx](https://github.com/Julio12-prog/TF_Algoritmos/files/6681230/Implementacion.de.las.estructuras.de.datos.docx)

**Comment by Pandaluf** [comment]
ya esta listo, falta revisar

**Comment by Pandaluf** [comment]
[Implementacion de las estructuras de datos.docx](https://github.com/Julio12-prog/TF_Algoritmos/files/6681257/Implementacion.de.las.estructuras.de.datos.docx)

**Comment by Pandaluf** [comment]
faltaba cambiar algunas partes

**Comment by Julio12-prog** [comment]
Completado y revisado.
